# Generated by Django 5.0.6 on 2024-05-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="email",
            field=models.CharField(
                blank=True, max_length=150, null=True, unique=True, verbose_name="Email"
            ),
        ),
    ]
